/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_euler;

import static java.lang.Math.sqrt;

/**
 *
 * @author Alexander Chelpanov
 * Date: 02.08.2019
 * 
 * 
 * The sequence of triangle numbers is generated by adding the natural numbers. 
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
 * The first ten terms would be:
 * 
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * 
 * Let us list the factors of the first seven triangle numbers:
 * 
 * 1: 1
 * 3: 1,3
 * 6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * 
 * We can see that 28 is the first triangle number to have over five divisors.
 * What is the value of the first triangle number to have over five hundred 
 * divisors?
 * 
 */
public class Task12 {
    public static void main(String[] args) {
        long num = 1;
        long count = 2;
        while (true) {
            num = num+count;
            
            if (howMuchDividers(num)>=500) {
                break;
            }
            count++;
        }
        System.out.println(num);
    }
    
    private static long howMuchDividers(long num) {
        long divs = 2;
        long counter = 2;
        double  newNum = (double)sqrt(num);
        if (newNum*newNum==num) {
            divs--;
        }
        while (counter<newNum) {
            if (num%counter==0) {
                divs=divs+2;
            }
            if (divs>=500) {
                break;
            }
            counter++;
        }
        return divs;
    }
    
}
